# Generated by Django 5.2.12 on 2026-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords for scanner', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
